analytics: {}
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 0.927364
name: GarageBuilt.Vegas
opengraph: {}
purpose: []
typography_spectrum: 1
